CREATE TABLE DEPOSITES(

	ACTNO INT,
	CNAME VARCHAR(50),
	BNAME VARCHAR(50),
	AMOUNT DECIMAL(8,2),
	ADATE DATETIME
)

CREATE TABLE BRANCHES(

	BNAME VARCHAR(50),
	CITY  VARCHAR(50)
)

INSERT INTO DEPOSITES

VALUES ( 101,'ANIL','VRCE',1000.00,'3-1-95'),
	   ( 102,'SUNIL','AJNI',5000.00,'1-4-96'),
	   ( 103,'MEHUL','KAROLBAGH',3500.00,'11-17-95'),
	   ( 104,'MADHURI','CHANDI',1200.00,'12-17-95'),
	   ( 105,'PRAMOD','M.G.ROAD',3000.00,'3-27-96'),
	   ( 106,'SANDIP','ANDHERI',2000.00,'3-31-96'),
	   ( 107,'SHIVANI','VIRAR',1000.00,'9-5-95'),
	   ( 108,'KRANTI','NEHRU PLACE',5000.00,'7-2-95'),
	   ( 109,'MINU','POWAI',7000.00,'8-10-95')

INSERT INTO BRANCHES

VALUES ( 'VRCE','NAGPUR'),
	   ( 'AJNI','NAGPUR'),
	   ( 'KAROLBAGH','DELHI'),
	   ( 'CHANDI','DELHI'),
	   ( 'DHARAMPETH','NAGPUR'),
	   ( 'M.G.ROAD','BANGLORE'),
	   ( 'ANDHERI','BOMBEY'),
	   ( 'VIRAR','BOMBAY'),
	   ( 'NEHRU PLACE','DELHI'),
	   ( 'POWAI','BOMBAY')

INSERT INTO CUSTOMERS

VALUES ( 'ANIL','CALCUTTA'),
	   ( 'SUNIL','DELHI'),
	   ( 'MEHUL','BARODA'),
	   ( 'MANDAR','PATNA'),
	   ( 'MADHURI','NAGPUR'),
	   ( 'PRAMOD','NAGPUR'),
	   ( 'SANDIP','SURAT'),
	   ( 'SHIVANI','BOMBAY'),
	   ( 'KRANTI','BOMBAY'),
	   ( 'NAREN','BOMBAY')

INSERT INTO BORROW

VALUES ( 201,'ANIL','VRCE',1000.00),
	   ( 206,'MEHUL','AJNI',5000.00),
	   ( 311,'SUNIL','DHARMPETH',3000.00),
	   ( 321,'MADHURI','ANDHERI',2000.00),
	   ( 375,'PRMOD','VIRAR',8000.00),
	   ( 481,'KRANTI','NEHRU PLACE',3000.00)

--2.1.
1. SELECT *FROM DEPOSITES;
2. SELECT *FROM BORROW;
3. SELECT *FROM CUSTOMERS;
4. SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITES;
5. SELECT LOANNO,AMOUNT FROM BORROW;
10. SELECT *FROM DEPOSITES WHERE ACTNO<105;
9. SELECT *FROM DEPOSITES WHERE ADATE>'1-12-96';
8. SELECT *FROM BORROW WHERE AMOUNT>5000;   
7. SELECT ACTNO,AMOUNT FROM DEPOSITES WHERE ACTNO=106; 
6. SELECT LOANNO FROM BORROW WHERE BNAME='ANDHERI'; 
11. SELECT CNAME FROM CUSTOMERS WHERE CITY IN ('NAGPUR','DELHI');
12. SELECT CNAME FROM  DEPOSITs WHERE AMOUNT>4000 AND ACTNO<105;
13. SELECT * FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 5000;
14. SELECT * FROM DEPOSITES WHERE  BNAME <> 'ANDHERI';
15. SELECT * FROM BORROW WHERE AMOUNT IS NULL;
16. SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITs WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104;
17. SELECT TOP 5 * FROM CUSTOMERS;
18. SELECT TOP 3 * FROM DEPOSITES WHERE AMOUNT>1000;
19. SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME <> 'ANDHERI';
20  SELECT DISTINCT CITY  FROM  CUSTOMERS;
21  SELECT DISTINCT BNAME FROM BRANCHS;
22. SELECT * FROM CUSTOMERS ORDER BY CITY;
23  SELECT * FROM DEPOSITES ORDER BY AMOUNT DESC; 
24. SELECT * FROM CUSTOMERS ORDER BY CITY DESC;
25. SELECT DISTINCT CNAME AS UNI_BORROWERS FROM BORROW;


--2.2

1. update DEPOSITES 
   set amount=5000
   where amount=3000;
   SELECT *FROM DEPOSITES;

2. update BORROW
   set bname='C.G.ROAD'
   WHERE CNAME='ANIL' AND BNAME='VRCE'; 
	SELECT *FROM BORROW;

3. UPDATE DEPOSITES
   SET ACTNO=111 , AMOUNT=5000
   WHERE ACTNO=106 AND AMOUNT=2000;

4. UPDATE BORROW
   SET AMOUNT=(AMOUNT+0.1*AMOUNT)

5. UPDATE DEPOSITES
   SET AMOUNT=5000
   WHERE ACTNO BETWEEN 103 AND 107;
  
6. UPDATE BORROW
   SET AMOUNT = NULL 
   WHERE LOANNO =321;

7. UPDATE BORROW
	SET LOANNO=401 , BNAME='AJNI'
	WHERE CNAME='ANIL';

8. UPDATE CUSTOMERS
   SET CNAME='ANIL JAIN'
   WHERE CNAME='ANIL';
   SELECT *FROM CUSTOMERS;

9. UPDATE DEPOSITES
   SET CNAME='RAMESH',BNAME='VRCE',AMOUNT=5500
   WHERE ACTNO=102;

10. UPDATE BORROW
    SET BNAME=NULL , AMOUNT=NULL
	WHERE LOANNO=481 AND CNAME='KRANTI';

--2.3

1. DELETE FROM CUSTOMERS
	WHERE CITY LIKE 'BOMBAY';

2. DELETE  FROM DEPOSITES
	WHERE AMOUNT<=1000;
	SELECT * FROM DEPOSITES;

3. DELETE FROM BORROW 
   WHERE BNAME='AJNI';
   SELECT * FROM BORROW;

4. DELETE FROM BORROW
   WHERE LOANNO BETWEEN 201 AND 210;

5. DELETE FROM DEPOSITES
   WHERE ADATE>'1996-12-1';

6. TRUNCATE TABLE CUSTOMERS;
	SELECT * FROM CUSTOMERS;

7. DELETE FROM DEPOSITES
   WHERE CNAME='ANIL' AND ACTNO=101;

8. DELETE FROM DEPOSITES 
	WHERE BNAME<>'ANDHERI';
	
9. DELETE FROM BORROW 
   WHERE AMOUNT< 2000 AND BNAME='VRCE'; 
    
10. DROP TABLE BRANCH;
	SELECT * FROM BRANCH;	